/*
	Example resource constant varible
*/


/* dialog */
#define IDD_OPEN			105
#define IDD_ABOUT                       106
#define IDD_WRITE_STAT                  107
#define IDD_READ_STAT                   108
#define IDD_FILETRANS                   109
#define IDD_STATUS                      110

/* dialog control */
#define IDC_STATIC			100
#define IDC_STATIC1                     101
#define IDC_STATIC2                     102
#define IDC_STATIC3                     103
#define IDC_STATIC4                     104
#define IDC_STATIC5                     105
#define IDC_STATIC6                     106
#define IDC_STATIC7                     107
#define IDC_STATIC8                     108
#define IDC_STATIC9                     109
#define IDC_STATIC10                    110
#define IDC_STATIC11                    111
#define IDC_STATIC12                    112
#define IDC_STATIC13                    113
#define IDC_STATIC14                    114


#define IDC_PORT                        1000
#define IDC_BAUD                        1001
#define IDC_PARITY                      1002
#define IDC_DATABITS                    1003
#define IDC_STOPBITS                    1004
#define IDC_HW                          1005
#define IDC_SW                          1006
#define IDC_DTR                         1007
#define IDC_RTS                         1008

#define IDC_WRITE_TYPE                  1009
#define IDC_WRITE_COUNT                 1010
#define IDC_WRITE_TIME                  1011
#define IDC_WRITE_CALLCNT               1012

#define IDC_READ_CALLCNT                1013
#define IDC_READ_TIME                   1014
#define IDC_READ_COUNT                  1015

#define IDC_X_PORT                      1024
#define IDC_X_PROTO                     1025
#define IDC_X_FNAME                     1026
#define IDC_X_FLEN                      1027
#define IDC_X_LEN                       1028
#define IDC_LEN_TEXT                    1029

#define IDC_ST_PORT                     1030
#define IDC_ST_BAUD                     1031
#define IDC_ST_FLOW                     1032
#define IDC_ST_PARITY                   1033
#define IDC_ST_DATABITS                 1034
#define IDC_ST_STOPBITS                 1035
#define IDC_ST_CTS                      1036
#define IDC_ST_DSR                      1037
#define IDC_ST_IQUEUE                   1038
#define IDC_ST_OQUEUE                   1039
#define IDC_ST_DATASTAT                 1040
#define IDC_ST_TIME                     1041
#define IDC_ST_RI                       1042
#define IDC_ST_DCD                      1043
#define IDC_ST_TXHOLD                   1044

#define IDC_FT_XMDM1KCRC                1045
#define IDC_FT_XMDMCHK                  1046
#define IDC_FT_XMDMCRC                  1047
#define IDC_FT_ZMDM                     1048
#define IDC_FT_YMDM                     1049
#define IDC_FT_KERMIT                   1050
#define IDC_FT_ASCII                    1051
#define IDC_FT_XMIT                     1052
#define IDC_FT_RECV                     1053

#define IDC_ABOUTSTR1                   1054
#define IDC_ABOUTSTR2                   1055


/* string resource */
#define IDS_BAUD50                      3
#define IDS_BAUD75                      4
#define IDS_BAUD110                     5
#define IDS_BAUD134                     6
#define IDS_BAUD150                     7
#define IDS_BAUD300                     8
#define IDS_BAUD600                     9
#define IDS_BAUD1200                    10
#define IDS_BAUD1800                    11
#define IDS_BAUD2400                    12
#define IDS_BAUD4800                    13
#define IDS_BAUD7200                    14
#define IDS_BAUD9600                    15
#define IDS_BAUD19200                   16
#define IDS_BAUD38400                   17
#define IDS_BAUD57600                   18
#define IDS_BAUD115200                  19
#define IDS_BAUD230400                  20
#define IDS_BAUD460800                  21
#define IDS_BAUD921600                  22

#define IDS_PARITYNONE                  23
#define IDS_PARITYEVEN                  24
#define IDS_PARITYODD                   25
#define IDS_PARITYMARK                  26
#define IDS_PARITYSPACE                 27

#define IDS_ONESTOPBIT                  28
#define IDS_TWOSTOPBITS                 29

#define IDS_DATABIT5                    30
#define IDS_DATABIT6                    31
#define IDS_DATABIT7                    32
#define IDS_DATABIT8                    33

#define IDS_TRAN_OK                     43
#define IDS_RECV_OK                     44
#define IDS_EBADPORT                    45
#define IDS_TTIMEOUT                    46
#define IDS_RTIMEOUT                    47
#define IDS_ABORT                       48
#define IDS_FOPEN                       49
#define IDS_CANABORT                    50
#define IDS_LACKBUF                     51
#define IDS_BOARDNOTSUPPORT             52
#define IDS_FTERR                       53

#define IDS_XMDM1KCRC                   54
#define IDS_XMDMCHK                     55
#define IDS_XMDMCRC                     56
#define IDS_ZMDM                        57
#define IDS_YMDM                        58
#define IDS_KERMIT                      59
#define IDS_ASCII                       60
#define IDS_XMIT                        61
#define IDS_RECV                        62

/* menu item */
#define IDM_SIMPLE                      105
#define IDM_FTRANS                      106
#define IDM_IRQDEMO                     107
#define IDM_PORTSTAT                    108
#define IDM_TIMEOUT                     109

#define IDM_PORT_OPEN                   40001
#define IDM_PORT_CLOSE                  40002
#define IDM_PORT_EXIT                   40003
#define IDM_PORT_SETTING                40004
#define IDM_HELP_ABOUT                  40005

#define IDM_FILE_TRANS                  40006
#define IDM_TXEMPTY                     40007

#define IDM_WRITE_POLL                  40009
#define IDM_WRITE_BLOCK                 40010
#define IDM_WRITE_TIMEOUT               40011
#define IDM_READ_POLL                   40012
#define IDM_READ_BLOCK                  40013
#define IDM_READ_BLOCK_T                40014
#define IDM_READ_BLOCK_I                40015
#define IDM_READ_BLOCK_TI               40016

#define IDM_PORT_STATUS                 40017

